config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :file_uploads, only: [:index, :new, :create, :destroy] do
    member do
      post :share
    end
  end

  root to: 'file_uploads#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  belongs_to :user

  validates :title, :file, presence: true
  validate :validate_file_size

  mount_uploader :file, FileUploader
  before_create :generate_shared_url

  private

  def validate_file_size
    if file.present? && file.size > 1.gigabytes
      errors.add(:file, "File size must be less than 1GB")
    end
  end

  def generate_shared_url
    self.shared_url = "https://short.url/#{SecureRandom.urlsafe_base64(10)}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :file_uploads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :excluded_controller?

  private

  def excluded_controller?
    devise_controller? || (request.path == new_user_session_path)
  end

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path, alert: 'You must sign in or sign up before continuing.'
    end
  end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_file_upload, only: [:destroy, :share]

  def index
    @file_uploads = current_user.file_uploads.order(created_at: :desc)
  end

  def new
    @file_upload = FileUpload.new
  end

  def create
    @file_upload = current_user.file_uploads.build(file_upload_params)

    if @file_upload.save
      redirect_to file_uploads_path, notice: 'File uploaded successfully.'
    else
      render :new, alert: @file_upload.errors.full_messages.to_sentence
    end
  end

  def destroy
    if @file_upload.destroy
      redirect_to file_uploads_path, notice: 'File deleted successfully.'
    else
      redirect_to file_uploads_path, alert: 'Error deleting file.'
    end
  end

  def share
    if @file_upload.shared_url
      redirect_to file_uploads_path, notice: "Shared URL: #{@file_upload.shared_url}"
    else
      redirect_to file_uploads_path, alert: 'Error generating shared URL.'
    end
  end

  private

  def set_file_upload
    @file_upload = current_user.file_uploads.find_by(id: params[:id])
    redirect_to file_uploads_path, alert: 'File not found.' unless @file_upload
  end

  def file_upload_params
    params.require(:file_upload).permit(:title, :description, :file)
  end

  def all_files
    @file_uploads = current_user.file_uploads
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate(auth_options)
    if resource.nil?
      flash[:alert] = 'Invalid email or password. Please sign up if you do not have an account.'
      redirect_to new_user_registration_path
    else
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/file_uploads/index.html.erb
<h1>Your Uploaded Files</h1>

<%= link_to 'Upload New File', new_file_upload_path, class: 'btn btn-primary' %>
<%= link_to 'Logout', logout_path, class: 'btn btn-secondary', data: { confirm: 'Are you sure you want to log out?' } %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @file_uploads.each do |file| %>
      <tr>
        <td><%= file.title %></td>
        <td><%= file.description %></td>
        <td>
          <%= link_to 'Delete', file_upload_path(file), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% if file.shared_url.present? %>
            <%= link_to 'Shared URL', file.shared_url, target: '_blank' %>
          <% else %>
            <%= button_to 'Share', share_file_upload_path(file), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/file_uploads/new.html.erb
<h1>Upload New File</h1>
<%= link_to 'Back to Files', file_uploads_path, class: 'btn btn-secondary' %>
<%= form_with model: @file_upload, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.submit 'Upload', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUploadSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>